"""Add blockchain fields

Revision ID: 4b2c503f7951
Revises: 
Create Date: 2025-10-15 14:25:23.881725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2c503f7951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockchain_token_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blockchain_block_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.drop_column('blockchain_block_number')
        batch_op.drop_column('blockchain_token_id')

    # ### end Alembic commands ###
